sonar.projectKey=sonar-node-app
sonar.projectName=Sonar Node App
sonar.projectVersion=1.0
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.login=squ_772314cd566f01c452ab599c70b7492f3f2fc3dc
